g_fileList = {
  "List": [
    {
      "Gender": "Female",
      "Part": "Bottom",
      "Files": [
        "Female/Bottom/Alien-Queen-Bottom.png",
        "Female/Bottom/Amazon-Leggings.png",
        "Female/Bottom/Barbarian-Leggings.png",
        "Female/Bottom/Black-Leather-Leggings.png",
        "Female/Bottom/Bloodmage-Dress.png",
        "Female/Bottom/Blue-Legging.png",
        "Female/Bottom/Challenger-Dominiel-Armor.png",
        "Female/Bottom/Challenger-Leggings.png",
        "Female/Bottom/Cyberpunk-Legging.png",
        "Female/Bottom/Darkmage-Dress.png",
        "Female/Bottom/Deedlit-Leggings.png",
        "Female/Bottom/Emo-Goth-Punk-Legging.png",
        "Female/Bottom/Fishnets-Legging.png",
        "Female/Bottom/Formal-Tuxedo-Legging.png",
        "Female/Bottom/Green-Fishnet-Leggings.png",
        "Female/Bottom/Green-Legging.png",
        "Female/Bottom/Kerrigan-Leggings.png",
        "Female/Bottom/Khaki-Shorts.png",
        "Female/Bottom/Kimono--Legging.png",
        "Female/Bottom/Kunimitsu-Legging.png",
        "Female/Bottom/Magical-Girl-Bottom.png",
        "Female/Bottom/Mechanic-Blue-Legging.png",
        "Female/Bottom/Metroid-Leggings.png",
        "Female/Bottom/Nier-Automata-Legging.png",
        "Female/Bottom/Orange-Skirt.png",
        "Female/Bottom/Priestess-Robe-Dress.png",
        "Female/Bottom/Priestess-Steel-Boots.png",
        "Female/Bottom/Ranger-Bottom.png",
        "Female/Bottom/Ranger-Leggings.png",
        "Female/Bottom/Samurai-Legging.png",
        "Female/Bottom/Samurai-Leggings.png",
        "Female/Bottom/Soldier-Army-Leggings.png",
        "Female/Bottom/White--Leggings.png",
        "Female/Bottom/Witcher-Leggings.png",
        "Female/Bottom/Yellow-Robe-Armor.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Eyes",
      "Files": [
        "Female/Eyes/Angry.png",
        "Female/Eyes/Bushy-Eyebrows.png",
        "Female/Eyes/Eyepatch.png",
        "Female/Eyes/Fiery-Stare.png",
        "Female/Eyes/Fiiery-Star.png",
        "Female/Eyes/Glasses-and-Eyebrows.png",
        "Female/Eyes/Happy.png",
        "Female/Eyes/Icy-Stare.png",
        "Female/Eyes/Mischief.png",
        "Female/Eyes/Original.png",
        "Female/Eyes/Poison.png",
        "Female/Eyes/Poison-Stare.png",
        "Female/Eyes/Scar.png",
        "Female/Eyes/Shellsocked.png",
        "Female/Eyes/Sneaky.png",
        "Female/Eyes/Sunglasses.png",
        "Female/Eyes/uwu-Eyes.png",
        "Female/Eyes/White-Glasses.png",
        "Female/Eyes/Winking.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Head",
      "Files": [
        "Female/Head/Bald-Hair.png",
        "Female/Head/Black-Cat.png",
        "Female/Head/Black-Hoodie.png",
        "Female/Head/Black-with-Ombre-Green-Tips-Hair.png",
        "Female/Head/Black-with-Ombre-Green-Tips-Long-Hair.png",
        "Female/Head/Blindfold.png",
        "Female/Head/Blonde-Bandana.png",
        "Female/Head/Blonde-Bun.png",
        "Female/Head/Brow-Hair.png",
        "Female/Head/Brown-Cat.png",
        "Female/Head/Brown-Hair.png",
        "Female/Head/Brown-Hair-with-Black-Green-Razer-Cat-Headphones.png",
        "Female/Head/Cat-Ears.png",
        "Female/Head/Centurion-Helmet.png",
        "Female/Head/Elecktra-Pony.png",
        "Female/Head/Green-Headset.png",
        "Female/Head/Green-Hoodie.png",
        "Female/Head/Green-Pony.png",
        "Female/Head/Headset.png",
        "Female/Head/High-Pony.png",
        "Female/Head/Kabuki-Makeup.png",
        "Female/Head/Kerrigan-Hair.png",
        "Female/Head/Light-Blond-Hair.png",
        "Female/Head/Long-Blond-Pigtails.png",
        "Female/Head/Mechanic-Brown-Rat.png",
        "Female/Head/Metroid-Helmet.png",
        "Female/Head/Metroid-Inspired-Helmet.png",
        "Female/Head/Mohawk-Data-Cables.png",
        "Female/Head/Ombre-Green-Long.png",
        "Female/Head/Ombre-Green-Short.png",
        "Female/Head/Orange-Hair.png",
        "Female/Head/Orange-Hair-with-Pink-Glasses.png",
        "Female/Head/Pony-with-Black-Green-Razer-Cat-Headphones.png",
        "Female/Head/Rat-Tail.png",
        "Female/Head/Red-Bandana.png",
        "Female/Head/Red-Head-Pony.png",
        "Female/Head/Sakura-Bandana.png",
        "Female/Head/Samurai-Helmet.png",
        "Female/Head/Short-White-Hair.png",
        "Female/Head/Soldier-Blonde-Hair.png",
        "Female/Head/Soldier-Brow-Hair.png",
        "Female/Head/Soldier-Brown-Hair.png",
        "Female/Head/Tomb-Raider-Hair.png",
        "Female/Head/Trinity-Hair.png",
        "Female/Head/Viking-Helmet.png",
        "Female/Head/White-Elven-Hair.png",
        "Female/Head/Wild-Hair.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Left Hand",
      "Files": [
        "Female/Left Hand/Axe-L.png",
        "Female/Left Hand/Battle-Guitar-L.png",
        "Female/Left Hand/Book-L.png",
        "Female/Left Hand/Claws-L.png",
        "Female/Left Hand/Crossbow-L.png",
        "Female/Left Hand/Crystal-Sword-L.png",
        "Female/Left Hand/Cyberpunk-Gun-L.png",
        "Female/Left Hand/Cyberpunk-Sword-L.png",
        "Female/Left Hand/Elecktra-Sai-L.png",
        "Female/Left Hand/Flying-Guillotine-L.png",
        "Female/Left Hand/Gloves-L.png",
        "Female/Left Hand/Glowing-Scroll-L.png",
        "Female/Left Hand/Gowing-Hands-L.png",
        "Female/Left Hand/Iron-Fan-L.png",
        "Female/Left Hand/Knight-Cross-L.png",
        "Female/Left Hand/Knight-Flaming-Sword-L.png",
        "Female/Left Hand/Knight-Sword-L.png",
        "Female/Left Hand/Kunai-L.png",
        "Female/Left Hand/Mage-Staff-L.png",
        "Female/Left Hand/Magical-Girl-Wand-L.png",
        "Female/Left Hand/Magical-Quill-L.png",
        "Female/Left Hand/Mechanic-Screwdriver-L.png",
        "Female/Left Hand/Mobile-Phone-L.png",
        "Female/Left Hand/None.png",
        "Female/Left Hand/Pistol-L.png",
        "Female/Left Hand/Poison-Sword-L.png",
        "Female/Left Hand/Priestess-Chalice-L.png",
        "Female/Left Hand/Ranger-Bow-L.png",
        "Female/Left Hand/Riffle-L.png",
        "Female/Left Hand/Rifle-L.png",
        "Female/Left Hand/Samurai-Katana-L.png",
        "Female/Left Hand/Scept-L.png",
        "Female/Left Hand/Scythe-L.png",
        "Female/Left Hand/Shuriken-L.png",
        "Female/Left Hand/Soldier-Riffle-L.png",
        "Female/Left Hand/Soldier-Rifle-L.png",
        "Female/Left Hand/Sword-L.png",
        "Female/Left Hand/Tomb-Raider-Pistol-L.png",
        "Female/Left Hand/Trident-L.png",
        "Female/Left Hand/Wakizashi-L.png",
        "Female/Left Hand/Wrench-L.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Mouth",
      "Files": [
        "Female/Mouth/Closed-Smile.png",
        "Female/Mouth/Flat.png",
        "Female/Mouth/Little-Smile.png",
        "Female/Mouth/Okay.png",
        "Female/Mouth/One-Fang.png",
        "Female/Mouth/Pucker.png",
        "Female/Mouth/Sad.png",
        "Female/Mouth/Smile.png",
        "Female/Mouth/Smiling.png",
        "Female/Mouth/Toothless.png",
        "Female/Mouth/Uwu-Mouth.png",
        "Female/Mouth/Vampire-Fangs.png",
        "Female/Mouth/Very-Sad.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Right Hand",
      "Files": [
        "Female/Right Hand/Arrow-R.png",
        "Female/Right Hand/Axe-R.png",
        "Female/Right Hand/Battle-Guitar-R.png",
        "Female/Right Hand/Buster-Cannon-R.png",
        "Female/Right Hand/Chainsaw-R.png",
        "Female/Right Hand/Claws-R.png",
        "Female/Right Hand/Crossbow-R.png",
        "Female/Right Hand/Cursed-Katana-R.png",
        "Female/Right Hand/Cyberpunk-Sword-R.png",
        "Female/Right Hand/Elecktra-Sai-R.png",
        "Female/Right Hand/Flying-Guillotine-R.png",
        "Female/Right Hand/Glowing-Hands-R.png",
        "Female/Right Hand/Glowing-Scroll-R.png",
        "Female/Right Hand/Iron-Fan-R.png",
        "Female/Right Hand/Knight-Shield-R.png",
        "Female/Right Hand/Lance-R.png",
        "Female/Right Hand/Laptop-Decker-R.png",
        "Female/Right Hand/Mace-R.png",
        "Female/Right Hand/Mage-Book-R.png",
        "Female/Right Hand/Mage-Staff-R.png",
        "Female/Right Hand/Magical-Quill-R.png",
        "Female/Right Hand/Martini-Glass-R.png",
        "Female/Right Hand/Metroid-Riffle-R.png",
        "Female/Right Hand/Metroid-Rifle-R.png",
        "Female/Right Hand/Mobile-Phone-R.png",
        "Female/Right Hand/None.png",
        "Female/Right Hand/Poison-Sword-R.png",
        "Female/Right Hand/Priestess-Hammer-R.png",
        "Female/Right Hand/Riffle-R.png",
        "Female/Right Hand/Rifle-R.png",
        "Female/Right Hand/Samurai-Katana-R.png",
        "Female/Right Hand/Scept-R.png",
        "Female/Right Hand/Screwdriver-R.png",
        "Female/Right Hand/Scythe-R.png",
        "Female/Right Hand/Shuriken-R.png",
        "Female/Right Hand/Snake-Staff-R.png",
        "Female/Right Hand/Soldier-Riffle-R.png",
        "Female/Right Hand/Soldier-Rifle-R.png",
        "Female/Right Hand/Staves-R.png",
        "Female/Right Hand/Strider-Sword-R.png",
        "Female/Right Hand/Tomb-Raider-Pistol-R.png",
        "Female/Right Hand/Trident-R.png",
        "Female/Right Hand/War-Hammer-R.png",
        "Female/Right Hand/Wrench-R.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Shadow",
      "Files": [
        "Female/Shadow/Base.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Skin",
      "Files": [
        "Female/Skin/Dark.png",
        "Female/Skin/Gold.png",
        "Female/Skin/Light.png",
        "Female/Skin/Metal.png",
        "Female/Skin/Orc.png",
        "Female/Skin/Zombie.png"
      ]
    },
    {
      "Gender": "Female",
      "Part": "Top",
      "Files": [
        "Female/Top/Alien-Queen-Top.png",
        "Female/Top/Amazon-Armor.png",
        "Female/Top/Bandage-Armor.png",
        "Female/Top/Barbarian-Armor.png",
        "Female/Top/Black-Hoodie-Armor.png",
        "Female/Top/Black-Leather-Jacket.png",
        "Female/Top/Bloodmage-Armor.png",
        "Female/Top/Challenger-Armor.png",
        "Female/Top/Challenger-Dominiel-Armor.png",
        "Female/Top/Cyberpunk-Armor.png",
        "Female/Top/Deedlit-Armor.png",
        "Female/Top/Emo-Goth-Punk-Armor.png",
        "Female/Top/Formal-Tuxedo-Armor.png",
        "Female/Top/Green-Hoodie-Armor.png",
        "Female/Top/Green-Vest.png",
        "Female/Top/Kerrigan-Armor.png",
        "Female/Top/Kimono-Armor.png",
        "Female/Top/Kunimitsu-Armor.png",
        "Female/Top/Leather-Jacket.png",
        "Female/Top/Magical-Girl-Top.png",
        "Female/Top/Mechanic-Sports-Bra.png",
        "Female/Top/Nier-Automata-Armor.png",
        "Female/Top/Orange-Armor.png",
        "Female/Top/Priestess-Armor.png",
        "Female/Top/Priestess-Robe.png",
        "Female/Top/Ranger-Top.png",
        "Female/Top/Ranger-Tunic.png",
        "Female/Top/Red-Armor.png",
        "Female/Top/Red-Priestess-Armor.png",
        "Female/Top/Samurai-Armor.png",
        "Female/Top/Soldier-Sleeveless-Armor.png",
        "Female/Top/Sports-Bra.png",
        "Female/Top/Tomb-Raider-Armor.png",
        "Female/Top/Turtleneck-Armor.png",
        "Female/Top/Witcher-Tunic.png",
        "Female/Top/Yellow-Robe.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Bottom",
      "Files": [
        "Male/Bottom/13k-Leggings.png",
        "Male/Bottom/Black-Muscle-Pants.png",
        "Male/Bottom/Black-Pants.png",
        "Male/Bottom/Blue-Army.png",
        "Male/Bottom/Blue-Sci-fi-Pants.png",
        "Male/Bottom/Boxers.png",
        "Male/Bottom/Camo-Army.png",
        "Male/Bottom/Cargo-Pants.png",
        "Male/Bottom/Conquest-Pants.png",
        "Male/Bottom/Defold-Leggings.png",
        "Male/Bottom/Denim-Pants.png",
        "Male/Bottom/Dragon-Boots.png",
        "Male/Bottom/Dragon-Pants.png",
        "Male/Bottom/Godot-Leggings.png",
        "Male/Bottom/Gold-Boots.png",
        "Male/Bottom/Green-Army.png",
        "Male/Bottom/Green-Pants.png",
        "Male/Bottom/Greensocks.png",
        "Male/Bottom/Green-Tactical.png",
        "Male/Bottom/Hero-Boots.png",
        "Male/Bottom/Ichigo-Pants.png",
        "Male/Bottom/Kirito-Leggings.png",
        "Male/Bottom/Knight-Boots.png",
        "Male/Bottom/Knight-Pants.png",
        "Male/Bottom/Lich.png",
        "Male/Bottom/Lich-Bottom.png",
        "Male/Bottom/Master-Chief-Pants.png",
        "Male/Bottom/Midnight-Army.png",
        "Male/Bottom/Niinja-Pants.png",
        "Male/Bottom/Ninja-Pants.png",
        "Male/Bottom/Orange-Army.png",
        "Male/Bottom/ORCA-Leggings.png",
        "Male/Bottom/Phaser-Bottom.png",
        "Male/Bottom/Primal-Leggings.png",
        "Male/Bottom/Purple-Pants.png",
        "Male/Bottom/Racing-Bottom.png",
        "Male/Bottom/Raging-Demon-Bottom.png",
        "Male/Bottom/Red-Boots.png",
        "Male/Bottom/Red-Ninja-Pants.png",
        "Male/Bottom/Sci-Fi--Pants.png",
        "Male/Bottom/Sci-Fi-Pants-2.png",
        "Male/Bottom/Silver-Boots.png",
        "Male/Bottom/Slacks.png",
        "Male/Bottom/Sports-Bottom.png",
        "Male/Bottom/Travis-Pants.png",
        "Male/Bottom/Tuxedo-Pants.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Eyes",
      "Files": [
        "Male/Eyes/Angry.png",
        "Male/Eyes/Bright-Eyed.png",
        "Male/Eyes/Bushy.png",
        "Male/Eyes/Demonic-Stare.png",
        "Male/Eyes/Fiery-Stare.png",
        "Male/Eyes/Glasses.png",
        "Male/Eyes/Happy.png",
        "Male/Eyes/Icy-Stare.png",
        "Male/Eyes/Poison-Stare.png",
        "Male/Eyes/Shades.png",
        "Male/Eyes/Shellshocked.png",
        "Male/Eyes/Sneaky.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Head",
      "Files": [
        "Male/Head/13k-Visor.png",
        "Male/Head/AR-Googles.png",
        "Male/Head/Beetle-Helmet.png",
        "Male/Head/Black-Bandana.png",
        "Male/Head/Blonde.png",
        "Male/Head/Blonde-Bandana.png",
        "Male/Head/Blonde-Buzzcut.png",
        "Male/Head/Blonde-Hero.png",
        "Male/Head/Bomber-Helm.png",
        "Male/Head/Buzzcut.png",
        "Male/Head/Cap-and-Dreads.png",
        "Male/Head/Conquest-Ape.png",
        "Male/Head/Cool-Hair.png",
        "Male/Head/Cyber-Mask.png",
        "Male/Head/Dark-Knight-Helmet.png",
        "Male/Head/Deadly-Mohawk.png",
        "Male/Head/Defold-Helm.png",
        "Male/Head/Dystopian-Mohawk.png",
        "Male/Head/Elven-Hair.png",
        "Male/Head/Floating-Crown.png",
        "Male/Head/Godot-Head.png",
        "Male/Head/Gray-Hood.png",
        "Male/Head/Green-Hood.png",
        "Male/Head/Helmet-Plume.png",
        "Male/Head/hood_green.png",
        "Male/Head/hood_purple.png",
        "Male/Head/HOUWAR.png",
        "Male/Head/Ichigo-Mask.png",
        "Male/Head/Knight-Helmet.png",
        "Male/Head/Knight-Helmet-2.png",
        "Male/Head/Law-Helm.png",
        "Male/Head/Lich.png",
        "Male/Head/Lich-Skull.png",
        "Male/Head/Long-Blonde-Hair.png",
        "Male/Head/male_hood.png",
        "Male/Head/male_long_white_hair.png",
        "Male/Head/male_Sorcerer's-Hat.png",
        "Male/Head/Male-Closed-Helmet.png",
        "Male/Head/Male-Saiyan.png",
        "Male/Head/Master-Chief-Helmet.png",
        "Male/Head/Megaman_Helmet.png",
        "Male/Head/Messy-Black-Hair.png",
        "Male/Head/Ninja-Mask.png",
        "Male/Head/Oni-Mask.png",
        "Male/Head/ORCA-Head.png",
        "Male/Head/Phaser-Head.png",
        "Male/Head/Powered-Up-Hair.png",
        "Male/Head/Primal-Hair.png",
        "Male/Head/Protag-Hair.png",
        "Male/Head/Purple-Hood.png",
        "Male/Head/Racing-Helmet.png",
        "Male/Head/Raging-Hair.png",
        "Male/Head/Red-Cap.png",
        "Male/Head/Ryu.png",
        "Male/Head/Samurai-Helmet.png",
        "Male/Head/SAO-Hair.png",
        "Male/Head/scifi_helmet.png",
        "Male/Head/Sci-Fi-Helmet.png",
        "Male/Head/Skull-Helmet.png",
        "Male/Head/Sorcerer-Hat.png",
        "Male/Head/Trafalgar-Helmet.png",
        "Male/Head/Trafalgar-Law-Helmet.png",
        "Male/Head/Travis-Head.png",
        "Male/Head/Visor.png",
        "Male/Head/Wanderer.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Left Hand",
      "Files": [
        "Male/Left Hand/Ammo-Belt-L.png",
        "Male/Left Hand/Arnis-L.png",
        "Male/Left Hand/Atomizer-Bat-L.png",
        "Male/Left Hand/Banana-Flag-L.png",
        "Male/Left Hand/Broadsword-L.png",
        "Male/Left Hand/Champagne-L.png",
        "Male/Left Hand/Crystal-Sword-L.png",
        "Male/Left Hand/Cybernetic-Arm-L.png",
        "Male/Left Hand/Cyber-Punk-Katana-L.png",
        "Male/Left Hand/Cypher-sword-L.png",
        "Male/Left Hand/Defold-Cross-L.png",
        "Male/Left Hand/Diamond-Hands-L.png",
        "Male/Left Hand/Dungeon-Knights-Sword-L.png",
        "Male/Left Hand/Energy-Blade.png",
        "Male/Left Hand/Energy-Sword-L.png",
        "Male/Left Hand/Flamethrower-L.png",
        "Male/Left Hand/Flying-Guillotine-L.png",
        "Male/Left Hand/Frostmorne-L.png",
        "Male/Left Hand/Frostmourne-L.png",
        "Male/Left Hand/Gauntlet-Cannon-L.png",
        "Male/Left Hand/Gauntlet-Canon-L.png",
        "Male/Left Hand/Godot-Hand-L.png",
        "Male/Left Hand/Gold-Gloves-L.png",
        "Male/Left Hand/Grenade-Launcher-L.png",
        "Male/Left Hand/Halo-Riffle-L.png",
        "Male/Left Hand/Halo-Rifle-L.png",
        "Male/Left Hand/Harry-Wand-L.png",
        "Male/Left Hand/Kirito-Sword-L.png",
        "Male/Left Hand/Knigh-Cross-L.png",
        "Male/Left Hand/Knight--Flaming-Sword-L.png",
        "Male/Left Hand/Knight-Sword-L.png",
        "Male/Left Hand/Knight-Whip-L.png",
        "Male/Left Hand/Kunai-L.png",
        "Male/Left Hand/Lich-Sword-L.png",
        "Male/Left Hand/Long-Sword-L.png",
        "Male/Left Hand/Mage-Book-2-L.png",
        "Male/Left Hand/Mage-Book-L.png",
        "Male/Left Hand/Mage-Staff-Green-L.png",
        "Male/Left Hand/Mage-Staff-L.png",
        "Male/Left Hand/None.png",
        "Male/Left Hand/Phaser-Alien-L.png",
        "Male/Left Hand/Pistol-L.png",
        "Male/Left Hand/Potion-L.png",
        "Male/Left Hand/Primal-Sword-L.png",
        "Male/Left Hand/Raging-Fist-L.png",
        "Male/Left Hand/Rifle-L.png",
        "Male/Left Hand/Rocket-Launcher-L.png",
        "Male/Left Hand/Scythe-L.png",
        "Male/Left Hand/Shield-L.png",
        "Male/Left Hand/Shuriken-L.png",
        "Male/Left Hand/Snake-Staff-L.png",
        "Male/Left Hand/Soda-Popper-L.png",
        "Male/Left Hand/Sonic-L.png",
        "Male/Left Hand/Spellbook-L.png",
        "Male/Left Hand/Sword-Ichigo-L.png",
        "Male/Left Hand/Sword-Right-R.png",
        "Male/Left Hand/Tool-Hand-L.png",
        "Male/Left Hand/Travis-Sword-L.png",
        "Male/Left Hand/Wand-L.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Mouth",
      "Files": [
        "Male/Mouth/Beard.png",
        "Male/Mouth/Cigar.png",
        "Male/Mouth/Flat.png",
        "Male/Mouth/Frowning.png",
        "Male/Mouth/Fullbeard.png",
        "Male/Mouth/Moustache.png",
        "Male/Mouth/Screaming.png",
        "Male/Mouth/Shouting.png",
        "Male/Mouth/Smiling.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Right Hand",
      "Files": [
        "Male/Right Hand/Arnis-R.png",
        "Male/Right Hand/Atomizer-Bat-R.png",
        "Male/Right Hand/AWP-R.png",
        "Male/Right Hand/Broadsword-R.png",
        "Male/Right Hand/Buster-Cannon-R.png",
        "Male/Right Hand/Buster-Sword-R.png",
        "Male/Right Hand/Conquest-Gun-R.png",
        "Male/Right Hand/Crystal-Sword-R.png",
        "Male/Right Hand/Cybernetic-Arm-R.png",
        "Male/Right Hand/Cyber-Punk-Katana-R.png",
        "Male/Right Hand/Cypher-sword-R.png",
        "Male/Right Hand/Defold-Cross-R.png",
        "Male/Right Hand/Desert-Eagle-R.png",
        "Male/Right Hand/Diamond-Hands-R.png",
        "Male/Right Hand/Disaster-Gun-R.png",
        "Male/Right Hand/Dungeon-Knights-Sword-R.png",
        "Male/Right Hand/Energy-Blade-R.png",
        "Male/Right Hand/Energy-Sword-R.png",
        "Male/Right Hand/Flying-Guillotine-R.png",
        "Male/Right Hand/Frostmorne-R.png",
        "Male/Right Hand/Frostmourne-R.png",
        "Male/Right Hand/Godot-Hand-R.png",
        "Male/Right Hand/Gold-Bracelet-R.png",
        "Male/Right Hand/Gold-Gloves-R.png",
        "Male/Right Hand/gunlance-R.png",
        "Male/Right Hand/Halo-beam-R.png",
        "Male/Right Hand/Heavy-Machine-Gun-R.png",
        "Male/Right Hand/Ichigo-sword-R.png",
        "Male/Right Hand/Kirito-Sword-R.png",
        "Male/Right Hand/Knight-Shield-R.png",
        "Male/Right Hand/Knight-Sword-R.png",
        "Male/Right Hand/Lance-R.png",
        "Male/Right Hand/Lich-Sword-R.png",
        "Male/Right Hand/Lightning-Axe.png",
        "Male/Right Hand/Longsword-R.png",
        "Male/Right Hand/Long-Sword-R.png",
        "Male/Right Hand/Mage-Book-R.png",
        "Male/Right Hand/Mage-Staff-Green-R.png",
        "Male/Right Hand/Mage-Staff-R.png",
        "Male/Right Hand/Mage-Wand-R.png",
        "Male/Right Hand/Martiini-Glass-R.png",
        "Male/Right Hand/None.png",
        "Male/Right Hand/Phaser-Alien-R.png",
        "Male/Right Hand/Phaser-Gun-R.png",
        "Male/Right Hand/Potion-Bottle-R.png",
        "Male/Right Hand/Primal-Gun-R.png",
        "Male/Right Hand/Raging-Fist-R.png",
        "Male/Right Hand/Rail-Gun-R.png",
        "Male/Right Hand/Rifle-R.png",
        "Male/Right Hand/Scythe-R.png",
        "Male/Right Hand/Shuriken-R.png",
        "Male/Right Hand/Snake-Staff-R.png",
        "Male/Right Hand/Soda-Popper-R.png",
        "Male/Right Hand/Sonic-R.png",
        "Male/Right Hand/Spellbook-R.png",
        "Male/Right Hand/Strider-Sword-R.png",
        "Male/Right Hand/Sword-Kight-R.png",
        "Male/Right Hand/Travis-Sword-R.png",
        "Male/Right Hand/Trophy-R.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Shadow",
      "Files": [
        "Male/Shadow/Base.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Skin",
      "Files": [
        "Male/Skin/Dark.png",
        "Male/Skin/Gold.png",
        "Male/Skin/Light.png",
        "Male/Skin/Metal.png",
        "Male/Skin/Orc.png",
        "Male/Skin/Zombie.png"
      ]
    },
    {
      "Gender": "Male",
      "Part": "Top",
      "Files": [
        "Male/Top/13k-Armor.png",
        "Male/Top/13k-Top.png",
        "Male/Top/Academy-Robe.png",
        "Male/Top/Akatsuki-Robe.png",
        "Male/Top/BB-Jersey.png",
        "Male/Top/Black-Muscle-Shirt.png",
        "Male/Top/Black-Tank.png",
        "Male/Top/Blue-Sci-Fi-Armor.png",
        "Male/Top/Blue-Shirt.png",
        "Male/Top/Blue-Tank.png",
        "Male/Top/Brown-Shirt.png",
        "Male/Top/BTC-Chain.png",
        "Male/Top/Common-Robe.png",
        "Male/Top/Conquest-Armor.png",
        "Male/Top/Cracked-Armor.png",
        "Male/Top/Defold-Armor.png",
        "Male/Top/Dragon-Armor.png",
        "Male/Top/Godot-Armor.png",
        "Male/Top/Gold-Armor.png",
        "Male/Top/Green-Tank.png",
        "Male/Top/Hogwards-Robe.png",
        "Male/Top/Ichigo-Robe.png",
        "Male/Top/Kirito-Armor.png",
        "Male/Top/Knight-Armor.png",
        "Male/Top/Lich-Robe.png",
        "Male/Top/Litch.png",
        "Male/Top/Mage-Robe.png",
        "Male/Top/Master-Chief.png",
        "Male/Top/Ninja-Armor.png",
        "Male/Top/Ninja-Armor-2.png",
        "Male/Top/Orange-Tank.png",
        "Male/Top/ORCA-Armor.png",
        "Male/Top/Phaser-Top.png",
        "Male/Top/Primal-Armor.png",
        "Male/Top/Purple-Robe.png",
        "Male/Top/Racing-Top.png",
        "Male/Top/Raging-Demon-Top.png",
        "Male/Top/Red-Ninja-Armor.png",
        "Male/Top/Red-Shirt.png",
        "Male/Top/Sci-Fi-Armor.png",
        "Male/Top/Sci-Fi-Armor-2.png",
        "Male/Top/Shirt.png",
        "Male/Top/Silver-Armor.png",
        "Male/Top/Starcraft-Marine.png",
        "Male/Top/Tank-Top-Gold-Chain.png",
        "Male/Top/Travis-Jacket.png",
        "Male/Top/Tuxedo.png",
        "Male/Top/Tuxedo_(007)_top.png",
        "Male/Top/Vest.png",
        "Male/Top/White-Ribe.png",
        "Male/Top/White-Robe.png"
      ]
    }
  ]
}
