g_config = {
	spritesheet: {
		/**Size of each individual sprite*/
		spriteWidth: 128,
		/**Size of each individual sprite*/
		spriteHeight: 128,

		/**How many frames to skip for the duration of the anim*/
		framesToSkip: 3,

		/**
		 * Default frame rate of the animations to play.
		 * Used with framesToSkip to generate properties.json
		 */
		defaultFrameRate: 60,

		/**
		 * Which animations to use as reference for the spritesheet.
		 * Their order in the array determines their vertical order on the sheet
		 */
		targetAnimations: ["Idle", "Walk", "Attack - Knight"],

		zipFileName: "YourArcadian.zip",
		spritesSubFolder: "sprites/",
		sheetfileName: "sheet.png",
		sheetJsonName: "properties.json",
	},

	list: [
		{
			id: "Male",
			gltfPath: "./gltf/Male/",
			gltfFileName: "ArcadianAvatar.gltf",
			position: { x: 0, y: -1, z: 0 },
			scaling: { x: 1, y: 1, z: -1 },
			materials: [
				{ id: "mat.mskin", name: "Skin" },
				{ id: "mat.meyes", name: "Eyes" },
				{ id: "mat.mhead", name: "Head" },
				{ id: "mat.mmouth", name: "Mouth" },
				{ id: "mat.mtop", name: "Top" },
				{ id: "mat.mleft", name: "Left Hand" },
				{ id: "mat.mright", name: "Right Hand" },
				{ id: "mat.mbot", name: "Bottom" },
				{ id: "mat.mshad", name: "Shadow" },
			],
			animations: [
				{ id: "m.idle", name: "Idle" },
				{ id: "m.walk", name: "Walk" },
				{ id: "m.talk", name: "Talk" },
				{ id: "m.talkpositive", name: "Talk - Positive" },
				{ id: "m.talknegative", name: "Talk - Negative" },
				{ id: "m.hit", name: "Hit" },
				{ id: "m.stun", name: "Stun" },
				{ id: "m.death", name: "Death" },
				{ id: "m.win", name: "Win" },
				{ id: "m.lose", name: "Lose" },
				{ id: "m.skillBuff", name: "Skill - Buff" },
				{ id: "m.skillMelee", name: "Skill - Melee" },
				{ id: "m.skillRanged", name: "Skill - Ranged" },
				{ id: "m.atkAss", name: "Attack - Assassin" },
				{ id: "m.atkGun", name: "Attack - Gunner" },
				{ id: "m.atkKni", name: "Attack - Knight" },
				{ id: "m.atkTec", name: "Attack - Tech" },
				{ id: "m.atkWiz", name: "Attack - Wizard" },
			],
		},
		{
			id: "Female",
			gltfPath: "./gltf/Female/",
			gltfFileName: "ArcadianAvatar - Female.gltf",
			position: { x: 0, y: -1, z: 0 },
			scaling: { x: 1, y: 1, z: -1 },
			materials: [
				{ id: "mat.femskin", name: "Skin" },
				{ id: "mat.femeyes", name: "Eyes" },
				{ id: "mat.femhead", name: "Head" },
				{ id: "mat.femmouth", name: "Mouth" },
				{ id: "mat.femtop", name: "Top" },
				{ id: "mat.femleft", name: "Left Hand" },
				{ id: "mat.femright", name: "Right Hand" },
				{ id: "mat.fembottom", name: "Bottom" },
				{ id: "mat.femshad", name: "Shadow" },
			],
			animations: [
				{ id: "f.idle", name: "Idle" },
				{ id: "f.walk", name: "Walk" },
				{ id: "f.talk", name: "Talk" },
				{ id: "f.talkpositive", name: "Talk - Positive" },
				{ id: "f.talknegative", name: "Talk - Negative" },
				{ id: "f.hit", name: "Hit" },
				{ id: "f.stun", name: "Stun" },
				{ id: "f.death", name: "Death" },
				{ id: "f.win", name: "Win" },
				{ id: "f.lose", name: "Lose" },
				{ id: "f.skillBuff", name: "Skill - Buff" },
				{ id: "f.skillMelee", name: "Skill - Melee" },
				{ id: "f.skillRanged", name: "Skill - Ranged" },
				{ id: "f.atkAss", name: "Attack - Assassin" },
				{ id: "f.atkGun", name: "Attack - Gunner" },
				{ id: "f.atkKni", name: "Attack - Knight" },
				{ id: "f.atkTec", name: "Attack - Tech" },
				{ id: "f.atkWiz", name: "Attack - Wizard" },
			],
		},
	],
};

g_fileList = {
	List: [
		{
			Gender: "Female",
			Part: "Bottom",
			Files: [
				"arcadian-parts/Female/Bottom/Alien-Queen-Bottom.png",
				"arcadian-parts/Female/Bottom/Amazon-Leggings.png",
				"arcadian-parts/Female/Bottom/Barbarian-Leggings.png",
				"arcadian-parts/Female/Bottom/Black-Leather-Leggings.png",
				"arcadian-parts/Female/Bottom/Bloodmage-Dress.png",
				"arcadian-parts/Female/Bottom/Blue-Legging.png",
				"arcadian-parts/Female/Bottom/Challenger-Dominiel-Armor.png",
				"arcadian-parts/Female/Bottom/Challenger-Leggings.png",
				"arcadian-parts/Female/Bottom/Cyberpunk-Legging.png",
				"arcadian-parts/Female/Bottom/Darkmage-Dress.png",
				"arcadian-parts/Female/Bottom/Deedlit-Leggings.png",
				"arcadian-parts/Female/Bottom/Emo-Goth-Punk-Legging.png",
				"arcadian-parts/Female/Bottom/Fishnets-Legging.png",
				"arcadian-parts/Female/Bottom/Formal-Tuxedo-Legging.png",
				"arcadian-parts/Female/Bottom/Green-Fishnet-Leggings.png",
				"arcadian-parts/Female/Bottom/Green-Legging.png",
				"arcadian-parts/Female/Bottom/Kerrigan-Leggings.png",
				"arcadian-parts/Female/Bottom/Khaki-Shorts.png",
				"arcadian-parts/Female/Bottom/Kimono--Legging.png",
				"arcadian-parts/Female/Bottom/Kunimitsu-Legging.png",
				"arcadian-parts/Female/Bottom/Magical-Girl-Bottom.png",
				"arcadian-parts/Female/Bottom/Mechanic-Blue-Legging.png",
				"arcadian-parts/Female/Bottom/Metroid-Leggings.png",
				"arcadian-parts/Female/Bottom/Nier-Automata-Legging.png",
				"arcadian-parts/Female/Bottom/Orange-Skirt.png",
				"arcadian-parts/Female/Bottom/Priestess-Robe-Dress.png",
				"arcadian-parts/Female/Bottom/Priestess-Steel-Boots.png",
				"arcadian-parts/Female/Bottom/Ranger-Bottom.png",
				"arcadian-parts/Female/Bottom/Ranger-Leggings.png",
				"arcadian-parts/Female/Bottom/Samurai-Legging.png",
				"arcadian-parts/Female/Bottom/Samurai-Leggings.png",
				"arcadian-parts/Female/Bottom/Soldier-Army-Leggings.png",
				"arcadian-parts/Female/Bottom/White--Leggings.png",
				"arcadian-parts/Female/Bottom/Witcher-Leggings.png",
				"arcadian-parts/Female/Bottom/Yellow-Robe-Armor.png",
			],
		},
		{
			Gender: "Female",
			Part: "Eyes",
			Files: [
				"arcadian-parts/Female/Eyes/Angry.png",
				"arcadian-parts/Female/Eyes/Bushy-Eyebrows.png",
				"arcadian-parts/Female/Eyes/Eyepatch.png",
				"arcadian-parts/Female/Eyes/Fiery-Stare.png",
				"arcadian-parts/Female/Eyes/Fiiery-Star.png",
				"arcadian-parts/Female/Eyes/Glasses-and-Eyebrows.png",
				"arcadian-parts/Female/Eyes/Happy.png",
				"arcadian-parts/Female/Eyes/Icy-Stare.png",
				"arcadian-parts/Female/Eyes/Mischief.png",
				"arcadian-parts/Female/Eyes/Original.png",
				"arcadian-parts/Female/Eyes/Poison.png",
				"arcadian-parts/Female/Eyes/Poison-Stare.png",
				"arcadian-parts/Female/Eyes/Scar.png",
				"arcadian-parts/Female/Eyes/Shellsocked.png",
				"arcadian-parts/Female/Eyes/Sneaky.png",
				"arcadian-parts/Female/Eyes/Sunglasses.png",
				"arcadian-parts/Female/Eyes/uwu-Eyes.png",
				"arcadian-parts/Female/Eyes/White-Glasses.png",
				"arcadian-parts/Female/Eyes/Winking.png",
			],
		},
		{
			Gender: "Female",
			Part: "Head",
			Files: [
				"arcadian-parts/Female/Head/Bald-Hair.png",
				"arcadian-parts/Female/Head/Black-Cat.png",
				"arcadian-parts/Female/Head/Black-Hoodie.png",
				"arcadian-parts/Female/Head/Black-with-Ombre-Green-Tips-Hair.png",
				"arcadian-parts/Female/Head/Black-with-Ombre-Green-Tips-Long-Hair.png",
				"arcadian-parts/Female/Head/Blindfold.png",
				"arcadian-parts/Female/Head/Blonde-Bandana.png",
				"arcadian-parts/Female/Head/Blonde-Bun.png",
				"arcadian-parts/Female/Head/Brow-Hair.png",
				"arcadian-parts/Female/Head/Brown-Cat.png",
				"arcadian-parts/Female/Head/Brown-Hair.png",
				"arcadian-parts/Female/Head/Brown-Hair-with-Black-Green-Razer-Cat-Headphones.png",
				"arcadian-parts/Female/Head/Cat-Ears.png",
				"arcadian-parts/Female/Head/Centurion-Helmet.png",
				"arcadian-parts/Female/Head/Elecktra-Pony.png",
				"arcadian-parts/Female/Head/Green-Headset.png",
				"arcadian-parts/Female/Head/Green-Hoodie.png",
				"arcadian-parts/Female/Head/Green-Pony.png",
				"arcadian-parts/Female/Head/Headset.png",
				"arcadian-parts/Female/Head/High-Pony.png",
				"arcadian-parts/Female/Head/Kabuki-Makeup.png",
				"arcadian-parts/Female/Head/Kerrigan-Hair.png",
				"arcadian-parts/Female/Head/Light-Blond-Hair.png",
				"arcadian-parts/Female/Head/Long-Blond-Pigtails.png",
				"arcadian-parts/Female/Head/Mechanic-Brown-Rat.png",
				"arcadian-parts/Female/Head/Metroid-Helmet.png",
				"arcadian-parts/Female/Head/Metroid-Inspired-Helmet.png",
				"arcadian-parts/Female/Head/Mohawk-Data-Cables.png",
				"arcadian-parts/Female/Head/Ombre-Green-Long.png",
				"arcadian-parts/Female/Head/Ombre-Green-Short.png",
				"arcadian-parts/Female/Head/Orange-Hair.png",
				"arcadian-parts/Female/Head/Orange-Hair-with-Pink-Glasses.png",
				"arcadian-parts/Female/Head/Pony-with-Black-Green-Razer-Cat-Headphones.png",
				"arcadian-parts/Female/Head/Rat-Tail.png",
				"arcadian-parts/Female/Head/Red-Bandana.png",
				"arcadian-parts/Female/Head/Red-Head-Pony.png",
				"arcadian-parts/Female/Head/Sakura-Bandana.png",
				"arcadian-parts/Female/Head/Samurai-Helmet.png",
				"arcadian-parts/Female/Head/Short-White-Hair.png",
				"arcadian-parts/Female/Head/Soldier-Blonde-Hair.png",
				"arcadian-parts/Female/Head/Soldier-Brow-Hair.png",
				"arcadian-parts/Female/Head/Soldier-Brown-Hair.png",
				"arcadian-parts/Female/Head/Tomb-Raider-Hair.png",
				"arcadian-parts/Female/Head/Trinity-Hair.png",
				"arcadian-parts/Female/Head/Viking-Helmet.png",
				"arcadian-parts/Female/Head/White-Elven-Hair.png",
				"arcadian-parts/Female/Head/Wild-Hair.png",
			],
		},
		{
			Gender: "Female",
			Part: "Left Hand",
			Files: [
				"arcadian-parts/Female/Left Hand/Axe-L.png",
				"arcadian-parts/Female/Left Hand/Battle-Guitar-L.png",
				"arcadian-parts/Female/Left Hand/Book-L.png",
				"arcadian-parts/Female/Left Hand/Claws-L.png",
				"arcadian-parts/Female/Left Hand/Crossbow-L.png",
				"arcadian-parts/Female/Left Hand/Crystal-Sword-L.png",
				"arcadian-parts/Female/Left Hand/Cyberpunk-Gun-L.png",
				"arcadian-parts/Female/Left Hand/Cyberpunk-Sword-L.png",
				"arcadian-parts/Female/Left Hand/Elecktra-Sai-L.png",
				"arcadian-parts/Female/Left Hand/Flying-Guillotine-L.png",
				"arcadian-parts/Female/Left Hand/Gloves-L.png",
				"arcadian-parts/Female/Left Hand/Glowing-Scroll-L.png",
				"arcadian-parts/Female/Left Hand/Gowing-Hands-L.png",
				"arcadian-parts/Female/Left Hand/Iron-Fan-L.png",
				"arcadian-parts/Female/Left Hand/Knight-Cross-L.png",
				"arcadian-parts/Female/Left Hand/Knight-Flaming-Sword-L.png",
				"arcadian-parts/Female/Left Hand/Knight-Sword-L.png",
				"arcadian-parts/Female/Left Hand/Kunai-L.png",
				"arcadian-parts/Female/Left Hand/Mage-Staff-L.png",
				"arcadian-parts/Female/Left Hand/Magical-Girl-Wand-L.png",
				"arcadian-parts/Female/Left Hand/Magical-Quill-L.png",
				"arcadian-parts/Female/Left Hand/Mechanic-Screwdriver-L.png",
				"arcadian-parts/Female/Left Hand/Mobile-Phone-L.png",
				"arcadian-parts/Female/Left Hand/None.png",
				"arcadian-parts/Female/Left Hand/Pistol-L.png",
				"arcadian-parts/Female/Left Hand/Poison-Sword-L.png",
				"arcadian-parts/Female/Left Hand/Priestess-Chalice-L.png",
				"arcadian-parts/Female/Left Hand/Ranger-Bow-L.png",
				"arcadian-parts/Female/Left Hand/Riffle-L.png",
				"arcadian-parts/Female/Left Hand/Rifle-L.png",
				"arcadian-parts/Female/Left Hand/Samurai-Katana-L.png",
				"arcadian-parts/Female/Left Hand/Scept-L.png",
				"arcadian-parts/Female/Left Hand/Scythe-L.png",
				"arcadian-parts/Female/Left Hand/Shuriken-L.png",
				"arcadian-parts/Female/Left Hand/Soldier-Riffle-L.png",
				"arcadian-parts/Female/Left Hand/Soldier-Rifle-L.png",
				"arcadian-parts/Female/Left Hand/Sword-L.png",
				"arcadian-parts/Female/Left Hand/Tomb-Raider-Pistol-L.png",
				"arcadian-parts/Female/Left Hand/Trident-L.png",
				"arcadian-parts/Female/Left Hand/Wakizashi-L.png",
				"arcadian-parts/Female/Left Hand/Wrench-L.png",
			],
		},
		{
			Gender: "Female",
			Part: "Mouth",
			Files: [
				"arcadian-parts/Female/Mouth/Closed-Smile.png",
				"arcadian-parts/Female/Mouth/Flat.png",
				"arcadian-parts/Female/Mouth/Little-Smile.png",
				"arcadian-parts/Female/Mouth/Okay.png",
				"arcadian-parts/Female/Mouth/One-Fang.png",
				"arcadian-parts/Female/Mouth/Pucker.png",
				"arcadian-parts/Female/Mouth/Sad.png",
				"arcadian-parts/Female/Mouth/Smile.png",
				"arcadian-parts/Female/Mouth/Smiling.png",
				"arcadian-parts/Female/Mouth/Toothless.png",
				"arcadian-parts/Female/Mouth/Uwu-Mouth.png",
				"arcadian-parts/Female/Mouth/Vampire-Fangs.png",
				"arcadian-parts/Female/Mouth/Very-Sad.png",
			],
		},
		{
			Gender: "Female",
			Part: "Right Hand",
			Files: [
				"arcadian-parts/Female/Right Hand/Arrow-R.png",
				"arcadian-parts/Female/Right Hand/Axe-R.png",
				"arcadian-parts/Female/Right Hand/Battle-Guitar-R.png",
				"arcadian-parts/Female/Right Hand/Buster-Cannon-R.png",
				"arcadian-parts/Female/Right Hand/Chainsaw-R.png",
				"arcadian-parts/Female/Right Hand/Claws-R.png",
				"arcadian-parts/Female/Right Hand/Crossbow-R.png",
				"arcadian-parts/Female/Right Hand/Cursed-Katana-R.png",
				"arcadian-parts/Female/Right Hand/Cyberpunk-Sword-R.png",
				"arcadian-parts/Female/Right Hand/Elecktra-Sai-R.png",
				"arcadian-parts/Female/Right Hand/Flying-Guillotine-R.png",
				"arcadian-parts/Female/Right Hand/Glowing-Hands-R.png",
				"arcadian-parts/Female/Right Hand/Glowing-Scroll-R.png",
				"arcadian-parts/Female/Right Hand/Iron-Fan-R.png",
				"arcadian-parts/Female/Right Hand/Knight-Shield-R.png",
				"arcadian-parts/Female/Right Hand/Lance-R.png",
				"arcadian-parts/Female/Right Hand/Laptop-Decker-R.png",
				"arcadian-parts/Female/Right Hand/Mace-R.png",
				"arcadian-parts/Female/Right Hand/Mage-Book-R.png",
				"arcadian-parts/Female/Right Hand/Mage-Staff-R.png",
				"arcadian-parts/Female/Right Hand/Magical-Quill-R.png",
				"arcadian-parts/Female/Right Hand/Martini-Glass-R.png",
				"arcadian-parts/Female/Right Hand/Metroid-Riffle-R.png",
				"arcadian-parts/Female/Right Hand/Metroid-Rifle-R.png",
				"arcadian-parts/Female/Right Hand/Mobile-Phone-R.png",
				"arcadian-parts/Female/Right Hand/None.png",
				"arcadian-parts/Female/Right Hand/Poison-Sword-R.png",
				"arcadian-parts/Female/Right Hand/Priestess-Hammer-R.png",
				"arcadian-parts/Female/Right Hand/Riffle-R.png",
				"arcadian-parts/Female/Right Hand/Rifle-R.png",
				"arcadian-parts/Female/Right Hand/Samurai-Katana-R.png",
				"arcadian-parts/Female/Right Hand/Scept-R.png",
				"arcadian-parts/Female/Right Hand/Screwdriver-R.png",
				"arcadian-parts/Female/Right Hand/Scythe-R.png",
				"arcadian-parts/Female/Right Hand/Shuriken-R.png",
				"arcadian-parts/Female/Right Hand/Snake-Staff-R.png",
				"arcadian-parts/Female/Right Hand/Soldier-Riffle-R.png",
				"arcadian-parts/Female/Right Hand/Soldier-Rifle-R.png",
				"arcadian-parts/Female/Right Hand/Staves-R.png",
				"arcadian-parts/Female/Right Hand/Strider-Sword-R.png",
				"arcadian-parts/Female/Right Hand/Tomb-Raider-Pistol-R.png",
				"arcadian-parts/Female/Right Hand/Trident-R.png",
				"arcadian-parts/Female/Right Hand/War-Hammer-R.png",
				"arcadian-parts/Female/Right Hand/Wrench-R.png",
			],
		},
		{
			Gender: "Female",
			Part: "Shadow",
			Files: ["arcadian-parts/Female/Shadow/Base.png"],
		},
		{
			Gender: "Female",
			Part: "Skin",
			Files: [
				"arcadian-parts/Female/Skin/Dark.png",
				"arcadian-parts/Female/Skin/Gold.png",
				"arcadian-parts/Female/Skin/Light.png",
				"arcadian-parts/Female/Skin/Metal.png",
				"arcadian-parts/Female/Skin/Orc.png",
				"arcadian-parts/Female/Skin/Zombie.png",
			],
		},
		{
			Gender: "Female",
			Part: "Top",
			Files: [
				"arcadian-parts/Female/Top/Alien-Queen-Top.png",
				"arcadian-parts/Female/Top/Amazon-Armor.png",
				"arcadian-parts/Female/Top/Bandage-Armor.png",
				"arcadian-parts/Female/Top/Barbarian-Armor.png",
				"arcadian-parts/Female/Top/Black-Hoodie-Armor.png",
				"arcadian-parts/Female/Top/Black-Leather-Jacket.png",
				"arcadian-parts/Female/Top/Bloodmage-Armor.png",
				"arcadian-parts/Female/Top/Challenger-Armor.png",
				"arcadian-parts/Female/Top/Challenger-Dominiel-Armor.png",
				"arcadian-parts/Female/Top/Cyberpunk-Armor.png",
				"arcadian-parts/Female/Top/Deedlit-Armor.png",
				"arcadian-parts/Female/Top/Emo-Goth-Punk-Armor.png",
				"arcadian-parts/Female/Top/Formal-Tuxedo-Armor.png",
				"arcadian-parts/Female/Top/Green-Hoodie-Armor.png",
				"arcadian-parts/Female/Top/Green-Vest.png",
				"arcadian-parts/Female/Top/Kerrigan-Armor.png",
				"arcadian-parts/Female/Top/Kimono-Armor.png",
				"arcadian-parts/Female/Top/Kunimitsu-Armor.png",
				"arcadian-parts/Female/Top/Leather-Jacket.png",
				"arcadian-parts/Female/Top/Magical-Girl-Top.png",
				"arcadian-parts/Female/Top/Mechanic-Sports-Bra.png",
				"arcadian-parts/Female/Top/Nier-Automata-Armor.png",
				"arcadian-parts/Female/Top/Orange-Armor.png",
				"arcadian-parts/Female/Top/Priestess-Armor.png",
				"arcadian-parts/Female/Top/Priestess-Robe.png",
				"arcadian-parts/Female/Top/Ranger-Top.png",
				"arcadian-parts/Female/Top/Ranger-Tunic.png",
				"arcadian-parts/Female/Top/Red-Armor.png",
				"arcadian-parts/Female/Top/Red-Priestess-Armor.png",
				"arcadian-parts/Female/Top/Samurai-Armor.png",
				"arcadian-parts/Female/Top/Soldier-Sleeveless-Armor.png",
				"arcadian-parts/Female/Top/Sports-Bra.png",
				"arcadian-parts/Female/Top/Tomb-Raider-Armor.png",
				"arcadian-parts/Female/Top/Turtleneck-Armor.png",
				"arcadian-parts/Female/Top/Witcher-Tunic.png",
				"arcadian-parts/Female/Top/Yellow-Robe.png",
			],
		},
		{
			Gender: "Male",
			Part: "Bottom",
			Files: [
				"arcadian-parts/Male/Bottom/13k-Leggings.png",
				"arcadian-parts/Male/Bottom/Black-Muscle-Pants.png",
				"arcadian-parts/Male/Bottom/Black-Pants.png",
				"arcadian-parts/Male/Bottom/Blue-Army.png",
				"arcadian-parts/Male/Bottom/Blue-Sci-fi-Pants.png",
				"arcadian-parts/Male/Bottom/Boxers.png",
				"arcadian-parts/Male/Bottom/Camo-Army.png",
				"arcadian-parts/Male/Bottom/Cargo-Pants.png",
				"arcadian-parts/Male/Bottom/Conquest-Pants.png",
				"arcadian-parts/Male/Bottom/Defold-Leggings.png",
				"arcadian-parts/Male/Bottom/Denim-Pants.png",
				"arcadian-parts/Male/Bottom/Dragon-Boots.png",
				"arcadian-parts/Male/Bottom/Dragon-Pants.png",
				"arcadian-parts/Male/Bottom/Godot-Leggings.png",
				"arcadian-parts/Male/Bottom/Gold-Boots.png",
				"arcadian-parts/Male/Bottom/Green-Army.png",
				"arcadian-parts/Male/Bottom/Green-Pants.png",
				"arcadian-parts/Male/Bottom/Greensocks.png",
				"arcadian-parts/Male/Bottom/Green-Tactical.png",
				"arcadian-parts/Male/Bottom/Hero-Boots.png",
				"arcadian-parts/Male/Bottom/Ichigo-Pants.png",
				"arcadian-parts/Male/Bottom/Kirito-Leggings.png",
				"arcadian-parts/Male/Bottom/Knight-Boots.png",
				"arcadian-parts/Male/Bottom/Knight-Pants.png",
				"arcadian-parts/Male/Bottom/Lich.png",
				"arcadian-parts/Male/Bottom/Lich-Bottom.png",
				"arcadian-parts/Male/Bottom/Master-Chief-Pants.png",
				"arcadian-parts/Male/Bottom/Midnight-Army.png",
				"arcadian-parts/Male/Bottom/Niinja-Pants.png",
				"arcadian-parts/Male/Bottom/Ninja-Pants.png",
				"arcadian-parts/Male/Bottom/Orange-Army.png",
				"arcadian-parts/Male/Bottom/ORCA-Leggings.png",
				"arcadian-parts/Male/Bottom/Phaser-Bottom.png",
				"arcadian-parts/Male/Bottom/Primal-Leggings.png",
				"arcadian-parts/Male/Bottom/Purple-Pants.png",
				"arcadian-parts/Male/Bottom/Racing-Bottom.png",
				"arcadian-parts/Male/Bottom/Raging-Demon-Bottom.png",
				"arcadian-parts/Male/Bottom/Red-Boots.png",
				"arcadian-parts/Male/Bottom/Red-Ninja-Pants.png",
				"arcadian-parts/Male/Bottom/Sci-Fi--Pants.png",
				"arcadian-parts/Male/Bottom/Sci-Fi-Pants-2.png",
				"arcadian-parts/Male/Bottom/Silver-Boots.png",
				"arcadian-parts/Male/Bottom/Slacks.png",
				"arcadian-parts/Male/Bottom/Sports-Bottom.png",
				"arcadian-parts/Male/Bottom/Travis-Pants.png",
				"arcadian-parts/Male/Bottom/Tuxedo-Pants.png",
			],
		},
		{
			Gender: "Male",
			Part: "Eyes",
			Files: [
				"arcadian-parts/Male/Eyes/Angry.png",
				"arcadian-parts/Male/Eyes/Bright-Eyed.png",
				"arcadian-parts/Male/Eyes/Bushy.png",
				"arcadian-parts/Male/Eyes/Demonic-Stare.png",
				"arcadian-parts/Male/Eyes/Fiery-Stare.png",
				"arcadian-parts/Male/Eyes/Glasses.png",
				"arcadian-parts/Male/Eyes/Happy.png",
				"arcadian-parts/Male/Eyes/Icy-Stare.png",
				"arcadian-parts/Male/Eyes/Poison-Stare.png",
				"arcadian-parts/Male/Eyes/Shades.png",
				"arcadian-parts/Male/Eyes/Shellshocked.png",
				"arcadian-parts/Male/Eyes/Sneaky.png",
			],
		},
		{
			Gender: "Male",
			Part: "Head",
			Files: [
				"arcadian-parts/Male/Head/13k-Visor.png",
				"arcadian-parts/Male/Head/AR-Googles.png",
				"arcadian-parts/Male/Head/Beetle-Helmet.png",
				"arcadian-parts/Male/Head/Black-Bandana.png",
				"arcadian-parts/Male/Head/Blonde.png",
				"arcadian-parts/Male/Head/Blonde-Bandana.png",
				"arcadian-parts/Male/Head/Blonde-Buzzcut.png",
				"arcadian-parts/Male/Head/Blonde-Hero.png",
				"arcadian-parts/Male/Head/Bomber-Helm.png",
				"arcadian-parts/Male/Head/Buzzcut.png",
				"arcadian-parts/Male/Head/Cap-and-Dreads.png",
				"arcadian-parts/Male/Head/Conquest-Ape.png",
				"arcadian-parts/Male/Head/Cool-Hair.png",
				"arcadian-parts/Male/Head/Cyber-Mask.png",
				"arcadian-parts/Male/Head/Dark-Knight-Helmet.png",
				"arcadian-parts/Male/Head/Deadly-Mohawk.png",
				"arcadian-parts/Male/Head/Defold-Helm.png",
				"arcadian-parts/Male/Head/Dystopian-Mohawk.png",
				"arcadian-parts/Male/Head/Elven-Hair.png",
				"arcadian-parts/Male/Head/Floating-Crown.png",
				"arcadian-parts/Male/Head/Godot-Head.png",
				"arcadian-parts/Male/Head/Gray-Hood.png",
				"arcadian-parts/Male/Head/Green-Hood.png",
				"arcadian-parts/Male/Head/Helmet-Plume.png",
				"arcadian-parts/Male/Head/hood_green.png",
				"arcadian-parts/Male/Head/hood_purple.png",
				"arcadian-parts/Male/Head/HOUWAR.png",
				"arcadian-parts/Male/Head/Ichigo-Mask.png",
				"arcadian-parts/Male/Head/Knight-Helmet.png",
				"arcadian-parts/Male/Head/Knight-Helmet-2.png",
				"arcadian-parts/Male/Head/Law-Helm.png",
				"arcadian-parts/Male/Head/Lich.png",
				"arcadian-parts/Male/Head/Lich-Skull.png",
				"arcadian-parts/Male/Head/Long-Blonde-Hair.png",
				"arcadian-parts/Male/Head/male_hood.png",
				"arcadian-parts/Male/Head/male_long_white_hair.png",
				"arcadian-parts/Male/Head/male_Sorcerer's-Hat.png",
				"arcadian-parts/Male/Head/Male-Closed-Helmet.png",
				"arcadian-parts/Male/Head/Male-Saiyan.png",
				"arcadian-parts/Male/Head/Master-Chief-Helmet.png",
				"arcadian-parts/Male/Head/Megaman_Helmet.png",
				"arcadian-parts/Male/Head/Messy-Black-Hair.png",
				"arcadian-parts/Male/Head/Ninja-Mask.png",
				"arcadian-parts/Male/Head/Oni-Mask.png",
				"arcadian-parts/Male/Head/ORCA-Head.png",
				"arcadian-parts/Male/Head/Phaser-Head.png",
				"arcadian-parts/Male/Head/Powered-Up-Hair.png",
				"arcadian-parts/Male/Head/Primal-Hair.png",
				"arcadian-parts/Male/Head/Protag-Hair.png",
				"arcadian-parts/Male/Head/Purple-Hood.png",
				"arcadian-parts/Male/Head/Racing-Helmet.png",
				"arcadian-parts/Male/Head/Raging-Hair.png",
				"arcadian-parts/Male/Head/Red-Cap.png",
				"arcadian-parts/Male/Head/Ryu.png",
				"arcadian-parts/Male/Head/Samurai-Helmet.png",
				"arcadian-parts/Male/Head/SAO-Hair.png",
				"arcadian-parts/Male/Head/scifi_helmet.png",
				"arcadian-parts/Male/Head/Sci-Fi-Helmet.png",
				"arcadian-parts/Male/Head/Skull-Helmet.png",
				"arcadian-parts/Male/Head/Sorcerer-Hat.png",
				"arcadian-parts/Male/Head/Trafalgar-Helmet.png",
				"arcadian-parts/Male/Head/Trafalgar-Law-Helmet.png",
				"arcadian-parts/Male/Head/Travis-Head.png",
				"arcadian-parts/Male/Head/Visor.png",
				"arcadian-parts/Male/Head/Wanderer.png",
			],
		},
		{
			Gender: "Male",
			Part: "Left Hand",
			Files: [
				"arcadian-parts/Male/Left Hand/Ammo-Belt-L.png",
				"arcadian-parts/Male/Left Hand/Arnis-L.png",
				"arcadian-parts/Male/Left Hand/Atomizer-Bat-L.png",
				"arcadian-parts/Male/Left Hand/Banana-Flag-L.png",
				"arcadian-parts/Male/Left Hand/Broadsword-L.png",
				"arcadian-parts/Male/Left Hand/Champagne-L.png",
				"arcadian-parts/Male/Left Hand/Crystal-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Cybernetic-Arm-L.png",
				"arcadian-parts/Male/Left Hand/Cyber-Punk-Katana-L.png",
				"arcadian-parts/Male/Left Hand/Cypher-sword-L.png",
				"arcadian-parts/Male/Left Hand/Defold-Cross-L.png",
				"arcadian-parts/Male/Left Hand/Diamond-Hands-L.png",
				"arcadian-parts/Male/Left Hand/Dungeon-Knights-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Energy-Blade.png",
				"arcadian-parts/Male/Left Hand/Energy-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Flamethrower-L.png",
				"arcadian-parts/Male/Left Hand/Flying-Guillotine-L.png",
				"arcadian-parts/Male/Left Hand/Frostmorne-L.png",
				"arcadian-parts/Male/Left Hand/Frostmourne-L.png",
				"arcadian-parts/Male/Left Hand/Gauntlet-Cannon-L.png",
				"arcadian-parts/Male/Left Hand/Gauntlet-Canon-L.png",
				"arcadian-parts/Male/Left Hand/Godot-Hand-L.png",
				"arcadian-parts/Male/Left Hand/Gold-Gloves-L.png",
				"arcadian-parts/Male/Left Hand/Grenade-Launcher-L.png",
				"arcadian-parts/Male/Left Hand/Halo-Riffle-L.png",
				"arcadian-parts/Male/Left Hand/Halo-Rifle-L.png",
				"arcadian-parts/Male/Left Hand/Harry-Wand-L.png",
				"arcadian-parts/Male/Left Hand/Kirito-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Knigh-Cross-L.png",
				"arcadian-parts/Male/Left Hand/Knight--Flaming-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Knight-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Knight-Whip-L.png",
				"arcadian-parts/Male/Left Hand/Kunai-L.png",
				"arcadian-parts/Male/Left Hand/Lich-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Long-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Mage-Book-2-L.png",
				"arcadian-parts/Male/Left Hand/Mage-Book-L.png",
				"arcadian-parts/Male/Left Hand/Mage-Staff-Green-L.png",
				"arcadian-parts/Male/Left Hand/Mage-Staff-L.png",
				"arcadian-parts/Male/Left Hand/None.png",
				"arcadian-parts/Male/Left Hand/Phaser-Alien-L.png",
				"arcadian-parts/Male/Left Hand/Pistol-L.png",
				"arcadian-parts/Male/Left Hand/Potion-L.png",
				"arcadian-parts/Male/Left Hand/Primal-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Raging-Fist-L.png",
				"arcadian-parts/Male/Left Hand/Rifle-L.png",
				"arcadian-parts/Male/Left Hand/Rocket-Launcher-L.png",
				"arcadian-parts/Male/Left Hand/Scythe-L.png",
				"arcadian-parts/Male/Left Hand/Shield-L.png",
				"arcadian-parts/Male/Left Hand/Shuriken-L.png",
				"arcadian-parts/Male/Left Hand/Snake-Staff-L.png",
				"arcadian-parts/Male/Left Hand/Soda-Popper-L.png",
				"arcadian-parts/Male/Left Hand/Sonic-L.png",
				"arcadian-parts/Male/Left Hand/Spellbook-L.png",
				"arcadian-parts/Male/Left Hand/Sword-Ichigo-L.png",
				"arcadian-parts/Male/Left Hand/Sword-Right-R.png",
				"arcadian-parts/Male/Left Hand/Tool-Hand-L.png",
				"arcadian-parts/Male/Left Hand/Travis-Sword-L.png",
				"arcadian-parts/Male/Left Hand/Wand-L.png",
			],
		},
		{
			Gender: "Male",
			Part: "Mouth",
			Files: [
				"arcadian-parts/Male/Mouth/Beard.png",
				"arcadian-parts/Male/Mouth/Cigar.png",
				"arcadian-parts/Male/Mouth/Flat.png",
				"arcadian-parts/Male/Mouth/Frowning.png",
				"arcadian-parts/Male/Mouth/Fullbeard.png",
				"arcadian-parts/Male/Mouth/Moustache.png",
				"arcadian-parts/Male/Mouth/Screaming.png",
				"arcadian-parts/Male/Mouth/Shouting.png",
				"arcadian-parts/Male/Mouth/Smiling.png",
			],
		},
		{
			Gender: "Male",
			Part: "Right Hand",
			Files: [
				"arcadian-parts/Male/Right Hand/Arnis-R.png",
				"arcadian-parts/Male/Right Hand/Atomizer-Bat-R.png",
				"arcadian-parts/Male/Right Hand/AWP-R.png",
				"arcadian-parts/Male/Right Hand/Broadsword-R.png",
				"arcadian-parts/Male/Right Hand/Buster-Cannon-R.png",
				"arcadian-parts/Male/Right Hand/Buster-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Conquest-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Crystal-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Cybernetic-Arm-R.png",
				"arcadian-parts/Male/Right Hand/Cyber-Punk-Katana-R.png",
				"arcadian-parts/Male/Right Hand/Cypher-sword-R.png",
				"arcadian-parts/Male/Right Hand/Defold-Cross-R.png",
				"arcadian-parts/Male/Right Hand/Desert-Eagle-R.png",
				"arcadian-parts/Male/Right Hand/Diamond-Hands-R.png",
				"arcadian-parts/Male/Right Hand/Disaster-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Dungeon-Knights-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Energy-Blade-R.png",
				"arcadian-parts/Male/Right Hand/Energy-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Flying-Guillotine-R.png",
				"arcadian-parts/Male/Right Hand/Frostmorne-R.png",
				"arcadian-parts/Male/Right Hand/Frostmourne-R.png",
				"arcadian-parts/Male/Right Hand/Godot-Hand-R.png",
				"arcadian-parts/Male/Right Hand/Gold-Bracelet-R.png",
				"arcadian-parts/Male/Right Hand/Gold-Gloves-R.png",
				"arcadian-parts/Male/Right Hand/gunlance-R.png",
				"arcadian-parts/Male/Right Hand/Halo-beam-R.png",
				"arcadian-parts/Male/Right Hand/Heavy-Machine-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Ichigo-sword-R.png",
				"arcadian-parts/Male/Right Hand/Kirito-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Knight-Shield-R.png",
				"arcadian-parts/Male/Right Hand/Knight-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Lance-R.png",
				"arcadian-parts/Male/Right Hand/Lich-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Lightning-Axe.png",
				"arcadian-parts/Male/Right Hand/Longsword-R.png",
				"arcadian-parts/Male/Right Hand/Long-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Mage-Book-R.png",
				"arcadian-parts/Male/Right Hand/Mage-Staff-Green-R.png",
				"arcadian-parts/Male/Right Hand/Mage-Staff-R.png",
				"arcadian-parts/Male/Right Hand/Mage-Wand-R.png",
				"arcadian-parts/Male/Right Hand/Martiini-Glass-R.png",
				"arcadian-parts/Male/Right Hand/None.png",
				"arcadian-parts/Male/Right Hand/Phaser-Alien-R.png",
				"arcadian-parts/Male/Right Hand/Phaser-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Potion-Bottle-R.png",
				"arcadian-parts/Male/Right Hand/Primal-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Raging-Fist-R.png",
				"arcadian-parts/Male/Right Hand/Rail-Gun-R.png",
				"arcadian-parts/Male/Right Hand/Rifle-R.png",
				"arcadian-parts/Male/Right Hand/Scythe-R.png",
				"arcadian-parts/Male/Right Hand/Shuriken-R.png",
				"arcadian-parts/Male/Right Hand/Snake-Staff-R.png",
				"arcadian-parts/Male/Right Hand/Soda-Popper-R.png",
				"arcadian-parts/Male/Right Hand/Sonic-R.png",
				"arcadian-parts/Male/Right Hand/Spellbook-R.png",
				"arcadian-parts/Male/Right Hand/Strider-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Sword-Kight-R.png",
				"arcadian-parts/Male/Right Hand/Travis-Sword-R.png",
				"arcadian-parts/Male/Right Hand/Trophy-R.png",
			],
		},
		{
			Gender: "Male",
			Part: "Shadow",
			Files: ["arcadian-parts/Male/Shadow/Base.png"],
		},
		{
			Gender: "Male",
			Part: "Skin",
			Files: [
				"arcadian-parts/Male/Skin/Dark.png",
				"arcadian-parts/Male/Skin/Gold.png",
				"arcadian-parts/Male/Skin/Light.png",
				"arcadian-parts/Male/Skin/Metal.png",
				"arcadian-parts/Male/Skin/Orc.png",
				"arcadian-parts/Male/Skin/Zombie.png",
			],
		},
		{
			Gender: "Male",
			Part: "Top",
			Files: [
				"arcadian-parts/Male/Top/13k-Armor.png",
				"arcadian-parts/Male/Top/13k-Top.png",
				"arcadian-parts/Male/Top/Academy-Robe.png",
				"arcadian-parts/Male/Top/Akatsuki-Robe.png",
				"arcadian-parts/Male/Top/BB-Jersey.png",
				"arcadian-parts/Male/Top/Black-Muscle-Shirt.png",
				"arcadian-parts/Male/Top/Black-Tank.png",
				"arcadian-parts/Male/Top/Blue-Sci-Fi-Armor.png",
				"arcadian-parts/Male/Top/Blue-Shirt.png",
				"arcadian-parts/Male/Top/Blue-Tank.png",
				"arcadian-parts/Male/Top/Brown-Shirt.png",
				"arcadian-parts/Male/Top/BTC-Chain.png",
				"arcadian-parts/Male/Top/Common-Robe.png",
				"arcadian-parts/Male/Top/Conquest-Armor.png",
				"arcadian-parts/Male/Top/Cracked-Armor.png",
				"arcadian-parts/Male/Top/Defold-Armor.png",
				"arcadian-parts/Male/Top/Dragon-Armor.png",
				"arcadian-parts/Male/Top/Godot-Armor.png",
				"arcadian-parts/Male/Top/Gold-Armor.png",
				"arcadian-parts/Male/Top/Green-Tank.png",
				"arcadian-parts/Male/Top/Hogwards-Robe.png",
				"arcadian-parts/Male/Top/Ichigo-Robe.png",
				"arcadian-parts/Male/Top/Kirito-Armor.png",
				"arcadian-parts/Male/Top/Knight-Armor.png",
				"arcadian-parts/Male/Top/Lich-Robe.png",
				"arcadian-parts/Male/Top/Litch.png",
				"arcadian-parts/Male/Top/Mage-Robe.png",
				"arcadian-parts/Male/Top/Master-Chief.png",
				"arcadian-parts/Male/Top/Ninja-Armor.png",
				"arcadian-parts/Male/Top/Ninja-Armor-2.png",
				"arcadian-parts/Male/Top/Orange-Tank.png",
				"arcadian-parts/Male/Top/ORCA-Armor.png",
				"arcadian-parts/Male/Top/Phaser-Top.png",
				"arcadian-parts/Male/Top/Primal-Armor.png",
				"arcadian-parts/Male/Top/Purple-Robe.png",
				"arcadian-parts/Male/Top/Racing-Top.png",
				"arcadian-parts/Male/Top/Raging-Demon-Top.png",
				"arcadian-parts/Male/Top/Red-Ninja-Armor.png",
				"arcadian-parts/Male/Top/Red-Shirt.png",
				"arcadian-parts/Male/Top/Sci-Fi-Armor.png",
				"arcadian-parts/Male/Top/Sci-Fi-Armor-2.png",
				"arcadian-parts/Male/Top/Shirt.png",
				"arcadian-parts/Male/Top/Silver-Armor.png",
				"arcadian-parts/Male/Top/Starcraft-Marine.png",
				"arcadian-parts/Male/Top/Tank-Top-Gold-Chain.png",
				"arcadian-parts/Male/Top/Travis-Jacket.png",
				"arcadian-parts/Male/Top/Tuxedo.png",
				"arcadian-parts/Male/Top/Tuxedo_(007)_top.png",
				"arcadian-parts/Male/Top/Vest.png",
				"arcadian-parts/Male/Top/White-Ribe.png",
				"arcadian-parts/Male/Top/White-Robe.png",
			],
		},
	],
};
